#!/bin/bash

module="proc_desc"
device="proc_desc"
mode="664"
device_nr=1


# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi


# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
/sbin/insmod ./$module.ko $* || exit 1


# retrieve major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)


# Remove stale nodes and replace them, then give gid and perms
for((i=0; i<device_nr; i++)) 
do
    rm -f /dev/${device}$i
    mknod /dev/${device}$i c $major $i
    chgrp $group /dev/${device}$i
    chmod $mode  /dev/${device}$i
done



